version: "3.9"
services:
  redis:
    image: redis:latest
    restart: always
    networks:
     - ashdavies
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8880:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    networks:
      - ashdavies
  wordpress:
    build:
      context: .
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env.wordpress
    volumes:
      - ./app/uploads/:/var/www/html/wp-content/uploads/
      - ./app/languages/:/var/www/html/wp-content/languages/
      - ./app/themes/:/var/www/html/wp-content/themes/
      - ./app/plugins/:/var/www/html/wp-content/plugins/
      - ./app/object-cache.php:/var/www/html/wp-content/object-cache.php
    networks:
      - ashdavies
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    env_file:
      - .env.mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - ashdavies

networks:
  ashdavies:

volumes:
  db:
