version: "3.9"
services:
  redis:
    image: redis:latest
    restart: always
    networks:
     - ashdavies
  wordpress:
    # image: ghcr.io/drizzlyowl/ashdavies.online/ashdavies:latest
    # image: wordpress:6
    image: ashdavies:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_ash
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* Custom rules */
        define( 'WP_REDIS_HOST', 'redis' );
    volumes:
      - ./app/uploads/:/var/www/html/wp-content/uploads/
      - ./app/languages/:/var/www/html/wp-content/languages/
      - ./app/themes/:/var/www/html/wp-content/themes/
      - ./app/plugins/:/var/www/html/wp-content/plugins/
      - ./app/object-cache.php:/var/www/html/wp-content/object-cache.php
    networks:
      - ashdavies
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/London
      - MYSQL_DATABASE=wp_ash
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - ashdavies

networks:
  ashdavies:

volumes:
  db:
