name: dependency-check

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-for-depen:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - uses: php-actions/composer@v5
      with:
        php_version: 7.4
        dev: no
    - uses: php-actions/composer@v5
      with:
        php_version: 7.4
        dev: no
        command: update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
