name: deployment-pipeline

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpcs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install phpcs
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpcs, phpcbf
      - uses: actions/checkout@v2
      - name: Run phpcs
        run: phpcs --standard=PSR12 $GITHUB_WORKSPACE/content/themes/**/*.php
      - name: Fix any issues if possible
        id: phpcbf
        run: phpcbf --standard=PSR12 --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 -w -v $GITHUB_WORKSPACE/content/themes/**/*.php
        continue-on-error: true
      - name: Merge corrected code
        run: |
          git config user.name "DrizzlyOwl"
          git config user.email "drizzlyowl@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git pull
          git commit -am "Automated phpcs fix"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  setup:
    needs: phpcs
    runs-on: ubuntu-20.04
    steps:
      - name: Install Deployer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: deployer
      - uses: actions/checkout@v2
      - name: Decrypt env
        env:
          GPG_KEY: ${{ secrets.ENV_KEY }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output .env .env.gpg
      - run: cat .env
