name: deployment-pipeline

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpcs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install PHP 7.4 & phpcs
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpcs
      - uses: actions/checkout@v2
      - run: phpcs --standard=PSR12 $GITHUB_WORKSPACE/content/themes/**/*.php
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Install PHP 7.4 & phpcs
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
            tools: wp, deployer, composer
      - uses: actions/checkout@v2
      - run: composer install --prefer-dist --no-progress
      - name: WP installation check
        run: wp --info
