name: deployment-pipeline

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpcs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: composer validate -d $GITHUB_WORKSPACE/.phpcs/ --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/.phpcs/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - run: composer install -d $GITHUB_WORKSPACE/.phpcs/ --prefer-dist --no-progress
      - run: $GITHUB_WORKSPACE/.phpcs/vendor/bin/phpcs --standard=PSR12 $GITHUB_WORKSPACE/content/themes/**/*.php
