name: deployment-pipeline

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpcs:
    runs-on: ubuntu-20.04
    working-directory: /tmp/
    steps:
      - uses: actions/checkout@v2
      - run: composer install -d ./.phpcs/ --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --no-suggest
      - run: pwd -P && ls -lah
      # - run: ./.phpcs/vendor/bin/phpcs --standard=PSR12 ./content/themes/**/*.php
